#!/usr/bin/env python
import yaml
import os
import tempfile
import sys

file_path = os.environ['YAML_FILE']

with open(file_path) as f:
    if sys.version_info[0] > 2:
        config = yaml.load(f, Loader=yaml.FullLoader)
    else:
        config = yaml.load(f)

fd, path = tempfile.mkstemp()

with os.fdopen(fd, 'w') as temp:
    for env in config['env']:
        os.environ[env] = config['env'][env]
        os.putenv(env, config['env'][env])
        temp.write('export {}="{}"\n'.format(env, config['env'][env]))

print(path)
